#!/bin/bash
# Quick Deploy to Render.com Script
# Run this after creating a Render.com account

echo "🚀 GraphRAG Production Deployment Helper"
echo "=========================================="
echo ""
echo "Step 1: Ensure GitHub is updated"
git status
echo ""
echo "Step 2: Go to Render Dashboard"
echo "   → https://dashboard.render.com"
echo ""
echo "Step 3: Click '+New' → 'Web Service'"
echo "   → Connect your GitHub account"
echo "   → Select 'graphrag-hackathon' repository"
echo ""
echo "Step 4: Configure with these settings:"
echo "   Branch: Main"
echo "   Runtime: Python 3.11"
echo "   Build Command: (Render will auto-detect from render.yaml)"
echo "   Start Command: (Render will auto-detect from render.yaml)"
echo "   Plan: Free (or Standard for better performance)"
echo ""
echo "Step 5: Click 'Create Web Service'"
echo "   → Render starts initial deployment"
echo "   → May show error about missing env vars (OK, expected)"
echo ""
echo "Step 6: Add Environment Variables"
echo "   → Go to Settings → Environment"
echo "   → Copy these from .env.production and add to Render:"
echo ""
echo "   TIGERGRAPH_HOST: $(grep TIGERGRAPH_HOST .env.production | cut -d= -f2)"
echo "   TIGERGRAPH_USERNAME: $(grep TIGERGRAPH_USERNAME .env.production | cut -d= -f2)"
echo "   TIGERGRAPH_PASSWORD: [YOUR PASSWORD]"
echo "   GOOGLE_API_KEY: [YOUR GEMINI KEY]"
echo ""
echo "Step 7: Save and redeploy"
echo "   → Render auto-redeploys when env vars are saved"
echo "   → Watch Logs tab for deployment progress"
echo ""
echo "Step 8: Test deployment"
echo "   → Wait for 'Live' status (5-10 min)"
echo "   → Visit: https://graphrag-backend.render.com"
echo "   → Should see dashboard"
echo ""
echo "✅ Done! Share link with judges:"
echo "   https://graphrag-backend.render.com"
