"""
Local Knowledge Graph — NetworkX-free graph with real 2-hop BFS traversal.
Used as a fallback when TigerGraph is unavailable, or as the primary graph
when running benchmarks locally.

The graph is loaded from a pre-built JSON file (data/knowledge_graph.json)
which is generated by scripts/build_knowledge_graph.py from the documents.
"""

import json
import logging
import re
from pathlib import Path
from collections import defaultdict

logger = logging.getLogger(__name__)


class LocalKnowledgeGraph:
    """
    In-memory knowledge graph with real multi-hop BFS traversal.
    Provides the same interface as TigerGraphClient for GraphRAG operations.
    """

    def __init__(self):
        self.entities = {}
        self.relationships = []
        self.adjacency = defaultdict(list)
        self.name_index = {}

    def load_from_json(self, path: str = None) -> "LocalKnowledgeGraph":
        """Load pre-built knowledge graph from JSON file."""
        if path is None:
            path = Path(__file__).resolve().parent.parent.parent / "data" / "knowledge_graph.json"
        else:
            path = Path(path)

        if not path.exists():
            logger.warning(f"Knowledge graph file not found: {path}")
            logger.info("Building graph from documents...")
            self._build_from_documents()
            return self

        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)

        for entity in data.get("entities", []):
            eid = entity["id"]
            self.entities[eid] = entity

            name_lower = entity.get("name", "").lower()
            self.name_index[name_lower] = eid

            for word in name_lower.split():
                if len(word) > 3 and word not in self.name_index:
                    self.name_index[word] = eid

        for rel in data.get("relationships", []):
            from_id = rel["from_id"]
            to_id = rel["to_id"]
            self.relationships.append(rel)
            self.adjacency[from_id].append((to_id, rel))
            self.adjacency[to_id].append((from_id, rel))

        logger.info(
            f"✅ Loaded local knowledge graph: {len(self.entities)} entities, "
            f"{len(self.relationships)} relationships"
        )

        return self

    def _build_from_documents(self):
        """Build graph from sample documents using regex extraction."""
        docs_dir = Path(__file__).resolve().parent.parent.parent / "data" / "sample_docs"
        if not docs_dir.exists():
            logger.warning(f"Sample docs directory not found: {docs_dir}")
            return

        all_text = ""
        for f in sorted(docs_dir.glob("*.md")):
            all_text += f.read_text(encoding="utf-8", errors="ignore") + "\n\n"

        terms = re.findall(r"\b([A-Z][a-z]+(?:\s+[A-Z][a-z]+)*)\b", all_text)
        term_counts = defaultdict(int)
        for t in terms:
            term_counts[t] += 1

        for name, count in sorted(term_counts.items(), key=lambda x: -x[1]):
            if count >= 2 and len(name) > 3:
                eid = re.sub(r"[^a-z0-9_]", "_", name.lower())
                self.entities[eid] = {
                    "id": eid,
                    "name": name,
                    "type": "CONCEPT",
                    "description": f"{name} (mentioned {count} times)",
                }
                self.name_index[name.lower()] = eid

        logger.info(f"Built graph with {len(self.entities)} entities from documents")

    def is_empty(self) -> bool:
        return len(self.entities) == 0

    def _match_entity(self, query_name: str) -> list[str]:
        """Find entity IDs matching a query name (fuzzy)."""
        query_lower = query_name.lower().strip()
        matches = []

        if query_lower in self.name_index:
            matches.append(self.name_index[query_lower])

        for name, eid in self.name_index.items():
            if eid in matches:
                continue
            if query_lower in name or name in query_lower:
                matches.append(eid)

        query_words = set(query_lower.split())
        for eid, entity in self.entities.items():
            if eid in matches:
                continue
            entity_words = set(entity["name"].lower().split())
            if query_words & entity_words:
                matches.append(eid)

        return matches[:5]

    def get_entity_subgraph(self, entity_names: list[str], max_hops: int = 2, max_neighbors: int = 10) -> dict:
        """
        Real 2-hop BFS traversal from seed entities.

        This is the CORE of GraphRAG — traverse the knowledge graph
        to discover structurally connected facts.

        Args:
            entity_names: Seed entity names extracted from the query
            max_hops: Number of hops to traverse (default 2)
            max_neighbors: Max neighbors per entity per hop

        Returns:
            Structured subgraph with entities and relationships
        """
        if not entity_names or self.is_empty():
            return {"entities": [], "relationships": [], "documents": []}

        seed_ids = set()
        for name in entity_names:
            matched = self._match_entity(name)
            seed_ids.update(matched)

        if not seed_ids:
            logger.debug(f"No entities matched for: {entity_names}")
            return {"entities": [], "relationships": [], "documents": []}

        logger.info(f"Seed entities: {len(seed_ids)} matched from {len(entity_names)} query terms")

        visited = set(seed_ids)
        frontier = set(seed_ids)
        collected_entities = set(seed_ids)
        collected_relationships = []
        seen_edges = set()

        for hop in range(max_hops):
            next_frontier = set()
            for node_id in frontier:
                neighbors = self.adjacency.get(node_id, [])

                sorted_neighbors = sorted(
                    neighbors,
                    key=lambda x: x[1].get("confidence", 0.5),
                    reverse=True,
                )

                for neighbor_id, edge_data in sorted_neighbors[:max_neighbors]:
                    edge_key = (
                        min(edge_data.get("from_id", node_id), edge_data.get("to_id", neighbor_id)),
                        max(edge_data.get("from_id", node_id), edge_data.get("to_id", neighbor_id)),
                        edge_data.get("type", "RELATED_TO"),
                    )
                    if edge_key not in seen_edges:
                        seen_edges.add(edge_key)
                        collected_relationships.append(edge_data)

                    collected_entities.add(neighbor_id)
                    if neighbor_id not in visited:
                        next_frontier.add(neighbor_id)

            visited.update(next_frontier)
            frontier = next_frontier

            logger.debug(f"Hop {hop + 1}: {len(next_frontier)} new entities, {len(collected_entities)} total")

        result_entities = []
        for eid in collected_entities:
            entity = self.entities.get(eid)
            if not entity:
                continue
            result_entities.append({
                "v_id": eid,
                "attributes": {
                    "name": entity.get("name", eid),
                    "entity_type": entity.get("type", "CONCEPT"),
                    "description": entity.get("description", ""),
                },
            })

        result_relationships = []
        for rel in collected_relationships[:20]:
            result_relationships.append({
                "from_id": rel.get("from_id", ""),
                "to_id": rel.get("to_id", ""),
                "attributes": {
                    "relation_type": rel.get("type", "RELATED_TO"),
                    "confidence": rel.get("confidence", 0.8),
                    "context": rel.get("context", ""),
                },
            })

        logger.info(f"✅ Subgraph retrieved: {len(result_entities)} entities, {len(result_relationships)} relationships ({max_hops}-hop traversal)")

        return {
            "entities": result_entities,
            "relationships": result_relationships,
            "documents": [],
        }

    def get_stats(self) -> dict:
        return {
            "vertices": len(self.entities),
            "edges": len(self.relationships),
            "graph": "LocalKnowledgeGraph",
        }
